### PR TITLE
Update dataset.py

### PR DESCRIPTION
**Pull request by evan-donovan**
Typo in heart class. thalachh to thalach

### CODE REVIEW

**Comment by mgilmore42** [comment]
The CSV seems to have 2 `h`s does yours only have 1?
image

**Comment by evan-donovan** [comment]
Mine only has one. I get an error when I try to run it

**Comment by evan-donovan** [comment]
image

Weird, the site shows it with 1 h when I look at it

**Comment by mgilmore42** [comment]
Looks like it changed from version 1 to version 2.

version 1

version 2

**Comment by evan-donovan** [comment]
Oh, my bad

**Pull request closed without merging**
